In [15]:
age = 26

In [19]:
name = "Alieu"
age = 25
h = 1.4
print(name)

Alieu


In [16]:
age

26

In [22]:
print(age)
print(name)
h

25
Alieu


1.4

In [23]:
#Import libarary
import os #
import numpy as np

In [24]:
#  create an array
a = np.array([1,2,34,46,89]) 
a

array([ 1,  2, 34, 46, 89])

In [28]:
type(a)

numpy.ndarray

In [27]:
# number of  elements
a.shape

(5,)

In [30]:
# indexing
a[4]

89

In [33]:
#  by pass error message
try:
    a[5]
except IndexError as e:
    print(e)

index 5 is out of bounds for axis 0 with size 5


In [34]:
# changing elements of an array
a[3] = 10
a

array([ 1,  2, 34, 10, 89])

In [44]:
b = np.array([[1,2,3], [3,5,7]])
b
type(b)
b.shape

(2, 3)

In [46]:
b = np.array([[1,2,3], [3,5,7], [1,20,30]])
b
type(b)
b.shape
b

array([[ 1,  2,  3],
       [ 3,  5,  7],
       [ 1, 20, 30]])

In [48]:
# flatten
c = np.hstack(b)
c

array([ 1,  2,  3,  3,  5,  7,  1, 20, 30])

In [55]:
#  matrix auto generate
np.zeros((4,2))
np.ones((4,2))
np.full((4,2), 13)

array([[13, 13],
       [13, 13],
       [13, 13],
       [13, 13]])

In [71]:
# generate random numbers
np.random.random((4,4))*5

TypeError: random() got an unexpected keyword argument 'dtype'

In [63]:
# from a list to an array & change the data type
a_list = [1,2,34]
a_list
d = np.array(a_list, dtype = float)
d

array([ 1.,  2., 34.])

In [70]:
# appending arrays
a = np.array([])
for i in range(50):
    a = np.append(a,i)
a

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [77]:
g = np.random.random((4,4))*100
g = g.round(0)
g

array([[91., 24., 93., 20.],
       [18., 29.,  3., 43.],
       [90., 95., 46., 55.],
       [21., 20., 46., 32.]])

In [79]:
# Locating elements
g[1,3]
g[3,1]

20.0

In [ ]:
 a = np.array()